# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='id')),
                ('paragraph', models.TextField(default='', verbose_name='段落内容')),
                ('count', models.IntegerField(default=0, verbose_name='计数')),
            ],
            options={
                'verbose_name': '段落信息',
                'verbose_name_plural': '段落信息',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题内容')),
                ('answer', models.TextField(verbose_name='答案内容')),
                ('paragraph_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='id')),
                ('paragraph', models.TextField(verbose_name='段落')),
            ],
            options={
                'verbose_name': '提交结果',
                'verbose_name_plural': '提交结果',
            },
        ),
    ]
